
package mmdc.homework4;

import java.text.DecimalFormat;

interface SalesItem {
    double calculateSales();
}

abstract class Item implements SalesItem {
    String name;
    double price;
    
    public Item (String name, double price) {
        this.name = name;
        this.price = price;
    }
    @Override
    public double calculateSales(){
        return 0;
    }
}

class Phone extends Item {
    int quantitySold;
    
    public Phone (String name, double price, int quantitySold) {
        super (name, price);
        this.quantitySold = quantitySold;
    }
    @Override
    public double calculateSales(){
        return price*quantitySold;
    }
     
}

class RepairService extends Item {
    int numberOfHours;
    
    public RepairService (String name, double price, int numberOfHours) {
        super (name, price);
        this.numberOfHours = numberOfHours;
    }
     @Override
    public double calculateSales(){
        return price*numberOfHours;
    }
}


public class Homework4 extends javax.swing.JFrame {

    public Homework4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtRSPrice = new javax.swing.JTextField();
        jBtnCalc = new javax.swing.JButton();
        jLblPItemName = new javax.swing.JLabel();
        jLblPPrice = new javax.swing.JLabel();
        jLblPQty = new javax.swing.JLabel();
        jLblRSTotal = new javax.swing.JLabel();
        jtxtPItemName = new javax.swing.JTextField();
        jLblPTotalSales = new javax.swing.JLabel();
        jtxtPPrice = new javax.swing.JTextField();
        jLblRSTotalSales = new javax.swing.JLabel();
        jtxtPQty = new javax.swing.JTextField();
        jLblRSItemName = new javax.swing.JLabel();
        jLblPhone = new javax.swing.JLabel();
        jLblRSPrice = new javax.swing.JLabel();
        jtxtRSQty = new javax.swing.JTextField();
        jLblRSHour = new javax.swing.JLabel();
        jLblPTotal = new javax.swing.JLabel();
        jtxtRSItemName = new javax.swing.JTextField();
        jLblRepairServices = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnCalc.setText("Calculate");
        jBtnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCalcActionPerformed(evt);
            }
        });

        jLblPItemName.setText("Item Name");

        jLblPPrice.setText("Price");

        jLblPQty.setText("Quantity Sold");

        jLblRSTotal.setText("Total Sales");

        jLblPTotalSales.setText("0");

        jLblRSTotalSales.setText("0");

        jLblRSItemName.setText("Item Name");

        jLblPhone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPhone.setText("Phones");

        jLblRSPrice.setText("Price per Hour");

        jLblRSHour.setText("Number of Hours");

        jLblPTotal.setText("Total Sales");

        jLblRepairServices.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblRepairServices.setText("Repair Services");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblRepairServices)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblPItemName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblPPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblPQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPQty, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblPTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblPTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLblRSHour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLblRSPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLblRSItemName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtRSQty, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtRSPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtRSItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblRSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCalc)
                            .addComponent(jLblRSTotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLblPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPItemName)
                    .addComponent(jtxtPItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPPrice)
                    .addComponent(jtxtPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblPQty)
                    .addComponent(jtxtPQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPTotal)
                    .addComponent(jLblPTotalSales))
                .addGap(18, 18, 18)
                .addComponent(jLblRepairServices)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblRSHour)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtRSItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblRSItemName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtRSPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblRSPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtRSQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRSTotal)
                    .addComponent(jLblRSTotalSales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCalc)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCalcActionPerformed
      double phonePrice = Double.parseDouble(jtxtPPrice.getText());
      int qtySold = Integer.parseInt(jtxtPQty.getText());
      
      double repairPrice = Double.parseDouble(jtxtRSPrice.getText());
      int numHours = Integer.parseInt(jtxtRSQty.getText());
      
      Phone phone = new Phone ("Phone",phonePrice,qtySold);
      RepairService repair = new RepairService ("Repair", repairPrice, numHours);
      
      DecimalFormat df = new DecimalFormat("#,###.##");
      
      jLblPTotalSales.setText(df.format(phone.calculateSales()));
      jLblRSTotalSales.setText(df.format(repair.calculateSales()));
    }//GEN-LAST:event_jBtnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homework4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homework4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homework4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homework4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homework4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCalc;
    private javax.swing.JLabel jLblPItemName;
    private javax.swing.JLabel jLblPPrice;
    private javax.swing.JLabel jLblPQty;
    private javax.swing.JLabel jLblPTotal;
    private javax.swing.JLabel jLblPTotalSales;
    private javax.swing.JLabel jLblPhone;
    private javax.swing.JLabel jLblRSHour;
    private javax.swing.JLabel jLblRSItemName;
    private javax.swing.JLabel jLblRSPrice;
    private javax.swing.JLabel jLblRSTotal;
    private javax.swing.JLabel jLblRSTotalSales;
    private javax.swing.JLabel jLblRepairServices;
    private javax.swing.JTextField jtxtPItemName;
    private javax.swing.JTextField jtxtPPrice;
    private javax.swing.JTextField jtxtPQty;
    private javax.swing.JTextField jtxtRSItemName;
    private javax.swing.JTextField jtxtRSPrice;
    private javax.swing.JTextField jtxtRSQty;
    // End of variables declaration//GEN-END:variables
}
